#!/usr/bin/env node
/**
 * CLI:  npm run generate [-- <source-root> [out-dir]]
 *
 * OUTPUT LAYOUT — built for 1000 components, not 10.
 *
 *   <out>/
 *     manifest.json                  every component, its status, its review items
 *     accountList/                   <- EXACT LWC bundle name, so the mapping
 *       AccountList.jsx                 back to source is unambiguous
 *       AccountList.module.css
 *       index.js                     re-export, so imports stay short
 *       MIGRATION.md                 provenance + what needs review
 *
 * One folder per LWC. A flat directory at this scale means 2000 files in one
 * place with no way to see which converted cleanly, and no obvious path back
 * to the original bundle. The folder name is the LWC name verbatim — not the
 * PascalCase React name — because the question being asked in six months is
 * "what happened to accountList", not "where did AccountList come from".
 *
 * Exit codes:
 *   0  every component converted with no review items
 *   1  at least one has review items (expected — a Tier-H refusal counts)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { findBundles } from '../census/lwc-census.js';
import { generateComponent } from './component.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = process.argv[2] || path.join(here, '..', 'force-app');
const outDir = process.argv[3]
    ? path.resolve(process.argv[3])
    : path.join(here, '..', 'react', 'generated');

fs.mkdirSync(outDir, { recursive: true });

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// Two passes: siblings must be known BEFORE generating any one component, or
// child imports cannot be emitted.
const bundles = findBundles(root).filter(
    (d) => fs.existsSync(path.join(d, `${path.basename(d)}.html`))
);
const knownComponents = new Set(bundles.map((d) => pascal(path.basename(d))));
// Component name -> its folder (the LWC bundle name), for cross-folder imports.
const componentDirs = new Map(bundles.map((d) => [pascal(path.basename(d)), path.basename(d)]));

let needsReview = 0;
let cssFiles = 0;
const manifest = [];

for (const dir of bundles) {
    const name = path.basename(dir);
    const jsPath = path.join(dir, `${name}.js`);
    const htmlPath = path.join(dir, `${name}.html`);

    const r = generateComponent({
        js: fs.readFileSync(jsPath, 'utf8'),
        html: fs.readFileSync(htmlPath, 'utf8'),
        name,
        knownComponents,
        componentDirs
    });

    // One folder per LWC, named exactly as the source bundle.
    const compDir = path.join(outDir, name);
    fs.mkdirSync(compDir, { recursive: true });

    fs.writeFileSync(path.join(compDir, `${r.componentName}.jsx`), r.code);
    if (r.usesStyles) {
        fs.writeFileSync(path.join(compDir, `${r.componentName}.module.css`), r.css);
        cssFiles++;
    }
    fs.writeFileSync(path.join(compDir, 'index.js'),
        `export { ${r.componentName} } from './${r.componentName}.jsx';\n`);

    const blocking = r.todos.filter(
        (t) => t.kind === 'tier-h' || t.kind === 'platform-escalate'
    );
    const status = r.todos.length === 0 ? 'clean'
        : (blocking.length ? 'escalated' : 'review');

    fs.writeFileSync(path.join(compDir, 'MIGRATION.md'), [
        `# ${name} → ${r.componentName}`,
        '',
        `**Status:** ${status}`,
        `**Source:** \`${path.relative(path.join(here, '..'), dir).replace(/\\/g, '/')}\``,
        `**Generated by:** \`codemod/component.js\` — do not edit by hand, regenerate.`,
        '',
        r.todos.length ? '## Review items\n' : '## No review items\n',
        ...r.todos.map((t) => `- **[${t.kind}]** ${t.detail}`),
        '',
        blocking.length
            ? '> These are **correct refusals**, not tool failures. A Tier-H component\n'
              + '> or an escalated platform module has no honest React equivalent —\n'
              + '> converting it would emit something plausible and wrong.'
            : ''
    ].join('\n'));

    if (r.todos.length) needsReview++;
    manifest.push({
        lwc: name,
        component: r.componentName,
        dir: name,
        status,
        hasStyles: Boolean(r.usesStyles),
        reviewItems: r.todos.length,
        todos: r.todos.map((t) => ({ kind: t.kind, detail: t.detail }))
    });
}

/* -------- manifest: the index you actually navigate at 1000 components ----- */

const byStatus = manifest.reduce((a, m) => { a[m.status] = (a[m.status] || 0) + 1; return a; }, {});
fs.writeFileSync(path.join(outDir, 'manifest.json'), `${JSON.stringify({
    generatedFrom: path.relative(path.join(here, '..'), root).replace(/\\/g, '/') || '.',
    total: manifest.length,
    byStatus,
    components: manifest.sort((a, b) => a.lwc.localeCompare(b.lwc))
}, null, 2)}\n`);

console.log(`Generated ${manifest.length} component(s), ${cssFiles} CSS module(s) -> ${outDir}\n`);
console.log(`  clean     ${byStatus.clean || 0}`);
console.log(`  review    ${byStatus.review || 0}`);
console.log(`  escalated ${byStatus.escalated || 0}   (correct refusals — Tier-H / host-only)`);
console.log(`\nOne folder per LWC. manifest.json indexes all ${manifest.length}.`);

if (needsReview) {
    console.log(`\n${manifest.length - needsReview}/${manifest.length} converted with no review items.`);
    process.exit(1);
}
console.log(`\nAll ${manifest.length} converted with no review items.`);
