#!/usr/bin/env node
/**
 * CLI:  npm run styles [-- <source-root> [preset]]
 *
 * Scans every LWC template, converts its SLDS classes, and writes
 * docs/slds-mapping-report.md — the "SLDS X becomes CSS Y" table teams review
 * before trusting the conversion, plus the unmapped list they act on.
 *
 * Exit 1 if anything is unmapped: an unmapped class is a silent visual
 * regression, so it should fail CI rather than sit in a report nobody opens.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { findBundles } from '../census/lwc-census.js';
import { convertClasses, formatMappingReport, SLDS } from './styles.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = process.argv[2] || path.join(here, '..', 'force-app');
const preset = process.argv[3] || SLDS.defaultPreset();

const results = [];
const perClassFiles = new Map();

for (const dir of findBundles(root)) {
    const name = path.basename(dir);
    const htmlPath = path.join(dir, `${name}.html`);
    if (!fs.existsSync(htmlPath)) continue;
    const html = fs.readFileSync(htmlPath, 'utf8');
    for (const m of html.matchAll(/class="([^"]+)"/g)) {
        const r = convertClasses(m[1], { preset });
        results.push(r);
        for (const cls of m[1].split(/\s+/).filter((c) => c.startsWith('slds-'))) {
            if (!perClassFiles.has(cls)) perClassFiles.set(cls, new Set());
            perClassFiles.get(cls).add(name);
        }
    }
}

const unmapped = new Set();
const lossy = new Set();
for (const r of results) {
    r.unmapped.forEach((u) => unmapped.add(u.cls));
    r.warnings.forEach((w) => lossy.add(w.cls));
}

const outDir = path.join(here, '..', 'docs');
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, 'slds-mapping-report.md');

const header = `# SLDS → React CSS mapping

Generated by \`npm run styles\`. **Do not edit** — change
[\`catalog/slds.xml\`](../catalog/slds.xml) and regenerate.

| | |
|---|---|
| Source | \`${path.relative(path.join(here, '..'), root).replace(/\\\\/g, '/')}\` |
| Preset | \`${preset}\`${SLDS.presets[preset].lossy ? ' — **lossy**' : ''} |
| Distinct SLDS classes | ${perClassFiles.size} |
| Unmapped | ${unmapped.size} |
| Lossy conversions | ${lossy.size} |

${SLDS.presets[preset].lossy
        ? `> ⚠️ **\`${preset}\` is a lossy preset.** ${SLDS.presets[preset].warnings.join(' ')}\n`
        : '> Density-preserving preset: `slds-var-*` classes keep working under Compact.\n'}
## How to read this

SLDS classes fall into families that convert **differently**:

- **Spacing** (\`slds-p-around_medium\`) → CSS declarations. The scale is
  **non-linear** — \`small\` is 0.75rem, not 1rem.
- **Density-aware spacing** (\`slds-var-*\`) → CSS custom properties. These drive
  Display Density; a fixed value would silently break Compact.
- **Component classes** (\`slds-card__header\`) → **dropped on purpose**. The
  component itself is replaced from \`catalog/base-components.xml\`, so emitting
  its CSS as well would style the element twice.
- **Unmapped** → nothing is emitted and it is listed below. Never silently dropped.

`;

fs.writeFileSync(outPath, header + formatMappingReport(results) + '\n');

console.log(`Preset: ${preset}${SLDS.presets[preset].lossy ? '  (LOSSY)' : ''}`);
console.log(`Distinct SLDS classes: ${perClassFiles.size}`);
console.log(`Unmapped: ${unmapped.size}`);
console.log(`Lossy:    ${lossy.size}`);
console.log(`\nWritten: ${outPath}`);

if (unmapped.size) {
    console.error('\nUNMAPPED CLASSES — each is a silent visual regression:');
    for (const c of [...unmapped].sort()) {
        console.error(`  ${c}   (${[...perClassFiles.get(c)].join(', ')})`);
    }
    console.error('\nAdd them to catalog/slds.xml.');
    process.exit(1);
}
